title: "IT & Virtuální asistence"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

markdown: kramdown

permalink: /:title/

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: it-style

sidebar:
  nav: "main"

sass:
  style: compressed

include:
  - assets/css/custom.scss


