title: "IT & Virtuální asistence"
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: it-style

sidebar:
  nav: "main"

include:
  - assets/css/custom.css

