title: "IT & Virtuální asistence"
theme: minimal-mistakes-jekyll

logo: /assets/images/favicon.png

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

markdown: kramdown

permalink: /:title/

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: it-style

sidebar:
  nav: "main"

sass:
  style: compressed

include:
  - assets/css/custom.scss





